USE online_quiz;

INSERT INTO `quizzes` VALUES (1, 'ปริศนาภาพลับสมอง ชุดที่ 1', 'ปริศนาภาพลับสมอง จากหนังสือ 103 Puzzle Quizzes โดย The Grabarchuk Family');
INSERT INTO `quizzes` VALUES (2, 'ปริศนาภาพลับสมอง ชุดที่ 2', 'ปริศนาภาพลับสมอง จากหนังสือ 103 Puzzle Quizzes โดย The Grabarchuk Family');
INSERT INTO `quizzes` VALUES (3, 'ทดสอบความรู้พื้นฐานด้านคอมพิวเตอร์ สำหรับเด็กคอม', 'ทดสอบความรู้พื้นฐานด้านคอมพิวเตอร์ สำหรับเด็กคอม โดยพร้อมเลิศ หล่อวิจิตร');

INSERT INTO `questions` VALUES (1, 1, 'สามเหลี่ยมแห่งตัวเลข', 'เลขที่ขาดหายไป (ตรงเครื่องหมาย ?) ควรเป็นเลขใด?', 'trio_numbers.png');
INSERT INTO `questions` VALUES (2, 1, 'นาฬิกา', 'นาฬิกาเรือนใดบอกเวลาไม่ถูกต้อง?', 'watches.png');
INSERT INTO `questions` VALUES (3, 1, 'คำที่ถูกซ่อนไว้', 'คำภาษาอังกฤษคำใดซ่อนอยู่ในเส้นตรงเหล่านี้?', 'hidden_word.png');
INSERT INTO `questions` VALUES (4, 1, 'สี่เหลี่ยมจตุรัส', 'สี่เหลี่ยมจตุรัสและกรอบสี่เหลี่ยมจตุรัส 2 รูปนี้ ประกอบขึ้นจากชิ้นส่วนต่างๆ จงหาว่ามีจำนวนชิ้นส่วนต่างกันอยู่เท่าไรระหว่าง 2 รูปนี้?', 'square.png');
INSERT INTO `questions` VALUES (5, 1, 'Bisection', 'รูปใดที่สามารถแบ่งออกเป็น 2 ส่วนที่เหมือนกันทุกประการได้ โดยต้องแบ่งตามแนวเส้นตรงเท่านั้น?', 'bisection.png');
INSERT INTO `questions` VALUES (6, 2, 'Wooden ABC', 'ตัวอักษรภาษาอังกฤษที่หายไป (ช่องเครื่องหมาย ?) ควรเป็นตัวอักษรใด?', 'wooden_abc.png');
INSERT INTO `questions` VALUES (7, 2, 'สร้างกรอบสี่เหลี่ยม', 'กรอบสี่เหลี่ยมสีเหลืองที่อยู่ตรงกลาง ถูกสร้างขึ้นจากชิ้นส่วน 3 ชิ้นที่มีตัวอักษร A ถึง D กำกับอยู่ จงหาว่าชิ้นส่วนใดที่ไม่ได้ถูกใช้?\\n\\nหมายเหตุ: ห้ามพลิกชิ้นส่วนหรือวางชิ้นส่วนซ้อนกัน', 'frame.png');
INSERT INTO `questions` VALUES (8, 2, 'ปริซึมกระดาษ', 'กระดาษรูปใด เมื่อพับตามแนวเส้นประแล้วจะได้รูปทรงปริซึม (prism) ที่อยู่ตรงกลางภาพนี้?\\n\\nหมายเหตุ: การพับจะต้องไม่มีส่วนใดของกระดาษที่ซ้อนทับกัน', 'prism.png');
INSERT INTO `questions` VALUES (9, 2, 'วงกลมและชิ้นส่วนวงกลม', 'รูปใดมีพื้นที่มากกว่า?', 'circle_segment.png');
INSERT INTO `questions` VALUES (10, 3, 'Nibble', 'คำว่า nibble (หรือเขียนว่า nybble หรือ nyble) หมายถึงข้อมูลขนาดกี่ไบต์ (byte)?', NULL);
INSERT INTO `questions` VALUES (11, 3, 'เลขฐานสอง', 'เลข 1011 ในระบบเลขฐานสอง มีค่าเท่ากับเลขใดในระบบเลขฐานสิบ?', 'binary.jpg');
INSERT INTO `questions` VALUES (12, 3, 'คุณรู้จักคอมพิวเตอร์ดีแค่ไหน', 'คำกล่าวเกี่ยวกับคอมพิวเตอร์ในข้อใดต่อไปนี้ไม่ถูกต้อง?', 'computers.png');
INSERT INTO `questions` VALUES (13, 3, 'Volatile Storage', 'ข้อใดจัดเป็นหน่วยเก็บข้อมูลแบบ volatile?', NULL);
INSERT INTO `questions` VALUES (14, 3, 'ผู้ก่อตั้งบริษัทไมโครซอฟท์', 'ใครคือผู้ก่อตั้งบริษัทไมโครซอฟท์ร่วมกับ Bill Gates?', 'microsoft_logo.jpg');
INSERT INTO `questions` VALUES (15, 3, 'Input Device', 'ข้อใดไม่ใช่ input device?', NULL);
INSERT INTO `questions` VALUES (16, 3, 'Lossy Compression', 'รูปแบบไฟล์ (file format) ประเภทใดที่มีการบีบอัดข้อมูลแบบ lossy?', NULL);
INSERT INTO `questions` VALUES (17, 3, 'Operating System', 'ข้อใดไม่ใช่ชื่อของระบบปฏิบัติการ (operating system)?', NULL);
INSERT INTO `questions` VALUES (18, 3, 'Signed Integer', 'Signed integer ขนาด 8 บิตจะมีค่าได้สูงสุดเท่าใด?', NULL);
INSERT INTO `questions` VALUES (19, 3, 'IBM', 'ชื่อบริษัท IBM ย่อมาจากอะไร?', 'ibm_logo.jpg');

INSERT INTO `choices` VALUES (1, 1, '5', 0);
INSERT INTO `choices` VALUES (2, 1, '6', 1);
INSERT INTO `choices` VALUES (3, 1, '7', 0);
INSERT INTO `choices` VALUES (4, 1, '8', 0);
INSERT INTO `choices` VALUES (5, 2, 'A', 0);
INSERT INTO `choices` VALUES (6, 2, 'B', 1);
INSERT INTO `choices` VALUES (7, 2, 'C', 0);
INSERT INTO `choices` VALUES (8, 2, 'ไม่มี', 0);
INSERT INTO `choices` VALUES (9, 3, 'Clock', 1);
INSERT INTO `choices` VALUES (10, 3, 'Mirror', 0);
INSERT INTO `choices` VALUES (11, 3, 'Piano', 0);
INSERT INTO `choices` VALUES (12, 3, 'Radio', 0);
INSERT INTO `choices` VALUES (13, 4, '0', 0);
INSERT INTO `choices` VALUES (14, 4, '1', 1);
INSERT INTO `choices` VALUES (15, 4, '2', 0);
INSERT INTO `choices` VALUES (16, 4, '3', 0);
INSERT INTO `choices` VALUES (17, 5, 'A', 0);
INSERT INTO `choices` VALUES (18, 5, 'B', 0);
INSERT INTO `choices` VALUES (19, 5, 'C', 0);
INSERT INTO `choices` VALUES (20, 5, 'D', 1);
INSERT INTO `choices` VALUES (21, 6, 'L', 0);
INSERT INTO `choices` VALUES (22, 6, 'M', 1);
INSERT INTO `choices` VALUES (23, 6, 'V', 0);
INSERT INTO `choices` VALUES (24, 6, 'X', 0);
INSERT INTO `choices` VALUES (25, 7, 'A', 0);
INSERT INTO `choices` VALUES (26, 7, 'B', 0);
INSERT INTO `choices` VALUES (27, 7, 'C', 1);
INSERT INTO `choices` VALUES (28, 7, 'D', 0);
INSERT INTO `choices` VALUES (29, 8, 'A', 0);
INSERT INTO `choices` VALUES (30, 8, 'B', 0);
INSERT INTO `choices` VALUES (31, 8, 'C', 1);
INSERT INTO `choices` VALUES (32, 8, 'D', 0);
INSERT INTO `choices` VALUES (33, 9, 'A', 0);
INSERT INTO `choices` VALUES (34, 9, 'B', 0);
INSERT INTO `choices` VALUES (35, 9, 'เท่ากัน', 1);
INSERT INTO `choices` VALUES (36, 10, 'ครึ่งไบต์', 1);
INSERT INTO `choices` VALUES (37, 10, '2 ไบต์', 0);
INSERT INTO `choices` VALUES (38, 10, '4 ไบต์', 0);
INSERT INTO `choices` VALUES (39, 10, '8 ไบต์', 0);
INSERT INTO `choices` VALUES (40, 10, '16 ไบต์', 0);
INSERT INTO `choices` VALUES (41, 11, '7', 0);
INSERT INTO `choices` VALUES (42, 11, '8', 0);
INSERT INTO `choices` VALUES (43, 11, '9', 0);
INSERT INTO `choices` VALUES (44, 11, '10', 0);
INSERT INTO `choices` VALUES (45, 11, '11', 1);
INSERT INTO `choices` VALUES (46, 12, 'คอมพิวเตอร์ฉลาดกว่ามนุษย์', 1);
INSERT INTO `choices` VALUES (47, 12, 'คอมพิวเตอร์ไม่สามารถทำงานได้ ถ้าหากเราไม่ป้อนคำสั่งให้มัน', 0);
INSERT INTO `choices` VALUES (48, 12, 'คอมพิวเตอร์ในปัจจุบันสามารถประมวลผลคำสั่งได้หลายล้านคำสั่งภายในเวลา 1 วินาที', 0);
INSERT INTO `choices` VALUES (49, 12, 'คอมพิวเตอร์ไม่สามารถตัดสินใจได้เอง', 0);
INSERT INTO `choices` VALUES (50, 12, 'คอมพิวเตอร์มีความแม่นยำในการคำนวณ 100%', 0);
INSERT INTO `choices` VALUES (51, 13, 'CD / DVD', 0);
INSERT INTO `choices` VALUES (52, 13, 'flash memory', 0);
INSERT INTO `choices` VALUES (53, 13, 'DRAM', 1);
INSERT INTO `choices` VALUES (54, 13, 'EPROM', 0);
INSERT INTO `choices` VALUES (55, 13, 'hard disk', 0);
INSERT INTO `choices` VALUES (56, 14, 'Steve Ballmer', 0);
INSERT INTO `choices` VALUES (57, 14, 'Steve Jobs', 0);
INSERT INTO `choices` VALUES (58, 14, 'Larry Page', 0);
INSERT INTO `choices` VALUES (59, 14, 'Paul Allen', 1);
INSERT INTO `choices` VALUES (60, 14, 'Steve Wozniak', 0);
INSERT INTO `choices` VALUES (61, 15, 'scanner', 0);
INSERT INTO `choices` VALUES (62, 15, 'printer', 1);
INSERT INTO `choices` VALUES (63, 15, 'microphone', 0);
INSERT INTO `choices` VALUES (64, 15, 'joystick', 0);
INSERT INTO `choices` VALUES (65, 15, 'barcode reader', 0);
INSERT INTO `choices` VALUES (66, 16, 'GIF', 0);
INSERT INTO `choices` VALUES (67, 16, 'PNG', 0);
INSERT INTO `choices` VALUES (68, 16, 'BMP', 0);
INSERT INTO `choices` VALUES (69, 16, 'ICO', 0);
INSERT INTO `choices` VALUES (70, 16, 'JPG', 1);
INSERT INTO `choices` VALUES (71, 17, 'Android', 0);
INSERT INTO `choices` VALUES (72, 17, 'Linux', 0);
INSERT INTO `choices` VALUES (73, 17, 'Macintosh', 1);
INSERT INTO `choices` VALUES (74, 17, 'Minix', 0);
INSERT INTO `choices` VALUES (75, 17, 'Unix', 0);
INSERT INTO `choices` VALUES (76, 18, '64', 0);
INSERT INTO `choices` VALUES (77, 18, '127', 1);
INSERT INTO `choices` VALUES (78, 18, '128', 0);
INSERT INTO `choices` VALUES (79, 18, '255', 0);
INSERT INTO `choices` VALUES (80, 18, '256', 0);
INSERT INTO `choices` VALUES (81, 19, 'Innovative Business Manufacture', 0);
INSERT INTO `choices` VALUES (82, 19, 'Innovative Broadband Manufacture', 0);
INSERT INTO `choices` VALUES (83, 19, 'International Business Machines', 1);
INSERT INTO `choices` VALUES (84, 19, 'International Business Manufacture', 0);
INSERT INTO `choices` VALUES (85, 19, 'ผิดทุกข้อ', 0);
